image: docker:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - cp .env-build-dist .env


build_push:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/<login>/<project>/<service> -f docker/nginx/DockerfileBuild .
    - docker push registry.gitlab.com/<login>/<project>/<service>

deploy-to-swarm:
  stage: deploy
  variables:
    DOCKER_HOST: $CI_DOCKER_HOST
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs"
  before_script:
    - rm -rf $DOCKER_CERT_PATH
    - mkdir $DOCKER_CERT_PATH
    - echo "$TLSCACERT" > $DOCKER_CERT_PATH/ca.pem
    - echo "$TLSCERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$TLSKEY" > $DOCKER_CERT_PATH/key.pem
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker stack deploy -c docker/docker-compose.deploy.yml --with-registry-auth  test
    - docker volume prune
    - rm -rf $DOCKER_CERT_PATH
  only:
    - master
