version: '3'

services:

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    env_file: ./../.env
    ports:
      - "8080:80"
    volumes:
      - ./../web/index.html:/usr/share/nginx/html/index.html

